on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 1-31 * *"

jobs:
  e2e-tests:
    runs-on: macos-latest # or macos-latest, windows-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2.5.1
        timeout-minutes: 1
        with:
          node-version: 16

      - uses: browser-actions/setup-chrome@latest
      - run: chrome --version

      - uses: microsoft/playwright-github-action@v1
      - name: run CodeceptJS tests
        run: |
          npm ci
          npm run test  
      
      - name: Send GitHub Action trigger data to Slack workflow
        if: failure()
        id: slack
        uses: slackapi/slack-github-action@v1.19.0
        with:
          payload: |
            {
              "text": "Automated job to make a recording has failed :pepe_fire: :pepe_fire: :pepe_fire: \n\n Link: https://github.com/morkoto1/makeRecording/actions"
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}    